//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ajax.Minifier.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Ajax.Minifier.Tasks.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not minify &apos;{0}&apos;: destination file &apos;{1}&apos; is read-only..
        /// </summary>
        internal static string DestinationIsReadOnly {
            get {
                return ResourceManager.GetString("DestinationIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not minify to destination file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string DidNotMinify {
            get {
                return ResourceManager.GetString("DidNotMinify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property value to AjaxMin build task: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidInputParameter {
            get {
                return ResourceManager.GetString("InvalidInputParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission to minify to destination file &apos;{0}&apos;.
        /// </summary>
        internal static string NoWritePermission {
            get {
                return ResourceManager.GetString("NoWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required AjaxMin build task property &apos;{0}&apos; is missing or empty..
        /// </summary>
        internal static string RequiredParameterIsEmpty {
            get {
                return ResourceManager.GetString("RequiredParameterIsEmpty", resourceCulture);
            }
        }
    }
}
